server {
    listen 443 ssl;
    server_name downloads.example.com;
    ssl_certificate /etc/letsencrypt/live/downloads.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/downloads.example.com/privkey.pem;

    client_max_body_size 160k;
    location / {
        proxy_pass http://127.0.0.1:8511;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 200s;
        proxy_send_timeout 200s;
        proxy_buffering off;
    }
}
