import { chromium } from '@playwright/test';
import { mkdirSync } from 'node:fs';
const browser = await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM || '/root/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});
const dir='/tmp/downkyi-workflow-screenshots';mkdirSync(dir,{recursive:true});
const results=[];
try {
for(const viewport of [{width:1440,height:1000},{width:390,height:844}]) {
  const page=await browser.newPage({viewport});const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const shot=async name=>{await page.screenshot({path:`${dir}/${name}-${viewport.width}.png`,fullPage:false});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error(`Overflow ${name} ${viewport.width}`)};
  const newDialog=async sample=>{await page.getByRole('button',{name:'新建下载',exact:true}).click();await page.getByRole('button',{name:sample,exact:true}).click();await page.getByRole('button',{name:'解析',exact:true}).click();await page.getByRole('heading',{name:'下载规格',exact:true}).waitFor();};
  await page.goto('http://127.0.0.1:8510/');await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0));
  if(!await page.locator('.variant-B').count()||await page.locator('.variant-switcher').count())throw Error('B layout not selected');
  await shot('queue');
  await page.getByRole('button',{name:'新建下载',exact:true}).click();await shot('step1');
  await page.getByRole('button',{name:'失效内容',exact:true}).click();await page.getByRole('button',{name:'解析',exact:true}).click();await page.getByRole('alert').waitFor();
  await page.getByRole('button',{name:'多 P 视频',exact:true}).click();await page.getByRole('button',{name:'解析',exact:true}).click();await page.getByRole('heading',{name:'下载规格',exact:true}).waitFor();
  if(!await page.locator('option[value="1080"]').isDisabled())throw Error('Anonymous 1080 should be locked');
  await page.getByRole('button',{name:'模拟登录',exact:true}).click();
  if(await page.locator('option[value="1080"]').isDisabled())throw Error('Logged-in 1080 should be unlocked');
  await page.getByLabel('可用字幕').check();await shot('step2-multipart');
  await page.getByRole('button',{name:'确认规格',exact:true}).click();
  const qualities=await page.locator('.review-table tbody tr td:nth-child(2)').allTextContents();
  if(qualities.join('|')!=='1080P|1080P|720P源画质上限')throw Error(`Wrong qualities ${qualities}`);
  await shot('step3');
  await page.getByRole('button',{name:'上一步',exact:true}).click();if(!await page.getByLabel('可用字幕').isChecked())throw Error('Back lost selection');
  await page.getByRole('button',{name:'确认规格',exact:true}).click();await page.getByRole('button',{name:'加入队列 (3)',exact:true}).click();
  if(await page.locator('.task-table tbody tr').count()!==8)throw Error('Queue did not get 3 tasks');
  await newDialog('多 P 视频');if(!await page.getByRole('button',{name:'确认规格',exact:true}).isDisabled())throw Error('Duplicates should be excluded');
  await page.getByRole('button',{name:'关闭弹窗',exact:true}).click();
  const taskRow=page.locator('.task-table tbody tr').filter({hasText:'山野影像集｜在自然里找回自己 · P1 · 山野之间'});
  await taskRow.getByRole('button',{name:'任务详情',exact:true}).click();
  for(let i=0;i<3;i++)await page.getByRole('button',{name:'推进演示阶段',exact:true}).click();
  if(!await page.locator('.detail-dialog .badge.merging').count())throw Error('Should merge after 100%');await shot('merging');
  await page.getByRole('button',{name:'推进演示阶段',exact:true}).click();
  if(await page.locator('.detail-dialog .file-row').count()!==3)throw Error('Expected video + cover + subtitles');await shot('files');
  await page.getByRole('button',{name:'移除记录',exact:true}).click();await page.getByRole('button',{name:'移除记录',exact:true}).click();
  await page.getByRole('button',{name:'已完成',exact:false}).first().click();
  const libraryRow=page.locator('.task-table tbody tr').filter({hasText:'山野影像集｜在自然里找回自己 · P1 · 山野之间'});
  if(!await libraryRow.count())throw Error('Record removal lost files');await libraryRow.getByRole('button',{name:'查看文件',exact:true}).click();
  if(await page.locator('.detail-dialog .file-row').count()!==3)throw Error('Files not retained');
  await page.getByRole('button',{name:'删除文件',exact:true}).click();if(!await page.getByRole('button',{name:'永久删除文件',exact:true}).isDisabled())throw Error('Delete needs confirmation');
  await page.getByLabel('我确认删除该任务的全部文件').check();await shot('delete-files');await page.getByRole('button',{name:'永久删除文件',exact:true}).click();
  if(await libraryRow.count())throw Error('File removal did not remove orphan');
  await page.getByRole('button',{name:'下载队列',exact:false}).first().click();
  await newDialog('视频合集');await shot('collection');if(await page.locator('.entry-row').count()!==5)throw Error('Collection entries missing');
  await page.getByRole('button',{name:'关闭弹窗',exact:true}).click();await newDialog('番剧');await shot('episodes');
  if(await page.locator('.entry-row input:disabled').count()!==2)throw Error('Paid/unreleased episodes should be disabled');
  await page.getByRole('button',{name:'关闭弹窗',exact:true}).click();await newDialog('单视频');
  await page.getByRole('button',{name:'仅音频',exact:true}).click();await page.getByLabel('视频封面').uncheck();
  await page.getByRole('button',{name:'确认规格',exact:true}).click();await shot('audio-review');await page.getByRole('button',{name:'加入队列 (1)',exact:true}).click();
  const audio=page.locator('.task-table tbody tr').filter({hasText:'仅音频'});await audio.getByRole('button',{name:'任务详情',exact:true}).click();
  if(!(await page.locator('.detail-info').innerText()).includes('仅音频 · M4A'))throw Error('Lost audio option');
  for(let i=0;i<4;i++)await page.getByRole('button',{name:'推进演示阶段',exact:true}).click();
  if(await page.locator('.file-row').count()!==1||!(await page.locator('.file-row').innerText()).includes('.m4a'))throw Error('Audio artifacts incorrect');
  if(errors.length)throw Error(errors.join('\n'));
  results.push({width:viewport.width,passed:true});await page.close();
}
console.log(JSON.stringify({results,screenshots:dir},null,2));
} finally {await browser.close();}
